### ISSUE TITLE
Code-a-website struggles!

### ISSUE THREAD

**Issue by Jessica-Lee123** [Jessica-Lee123/code-a-website#1]
Hey Chelle, 
So I think I'm doing pretty good, better than I thought, BUT, I'm stuck. 
My images are all broken, it shows them as a broken image box. 
My home link from those pages didn't work either. 
Otherwise, I know I have some fonts to fix up, but otherwise, honestly, I'm pretty impressed I was able to do this much. Thanks to all your extra help of course! 
No rush, hope you have an awesome break!

**Comment by Jessica-Lee123** [comment]
Shoot! Forgot to tag you, @hellachella 
I'll re-past my previous convo incase you can't see it. 
"Hey Chelle,
So I think I'm doing pretty good, better than I thought, BUT, I'm stuck.
My images are all broken, it shows them as a broken image box.
My home link from those pages didn't work either.
Otherwise, I know I have some fonts to fix up, but otherwise, honestly, I'm pretty impressed I was able to do this much. Thanks to all your extra help of course!
No rush, hope you have an awesome break!"

**Comment by hellachella** [comment]
I think you need to commit your most recent work because I'm not seeing any pages besides index.html

**Comment by Jessica-Lee123** [comment]
@hellachella

**Comment by hellachella** [comment]
Berries folder should be lowercase. You will have to change it and then change it everywhere in your file that you've used uppercase in your paths.

**Comment by Jessica-Lee123** [comment]
@hellachella Hey Hey Hey! 👯
